# Request a login link
curl -X POST http://localhost:8000/api/auth/request-link \
  -H "Content-Type: application/json" \
  -d '{"email": "reader@stry.com"}'

#### grab genres
curl http://localhost:8000/api/stories/genres


#### grab a story 
curl http://localhost:8000/api/stories/et-dolor-repellat-808

#### grab all stories
curl http://localhost:8000/api/stories

#### get an authenticated user 
curl http://localhost:8000/api/user